### ISSUE TITLE
Add Python 3 suppport

### ISSUE THREAD

**Issue by IvanAnishchuk** [graham/python_xid#1]
Isn't it, like, 2017 already? A few workarounds will be needed needed to support both py2 nd py3 but, actually, pure py3 code would've been simpler because bytes essentially is a byte array, no `map(ord, ...)` needed.

**Comment by graham** [comment]
agreed, i'll make the changes and update (old habits die hard).

**Comment by graham** [comment]
Relevant change from https://github.com/mguentner  https://github.com/graham/base32hex/commit/57b12c54250d8ded057412c436efe8358404260d

**Comment by silkentrance** [comment]
@graham I created a PR for this, see #2 for more information

**Comment by graham** [comment]
Hi Carsten, I'm out of town until Sunday but I'll get this resolved as soon
as I'm back

**Comment by xulei890817** [comment]
It's a nice lib,small and pretty,
and i still need python3 support.

**Comment by graham** [comment]
Thanks to https://github.com/graham/python_xid/commit/a0778575e918ff8dfb2c63e2bdf4fe340da0b764 @silkentrance -> python 3 is now supported.

**Comment by silkentrance** [comment]
@xulei890817 python 2 and 3 are now supported

**Comment by askogvold** [comment]
@graham Could this be released as a new version on PyPI as well? latest=1.0.4, which does not have this update

Thanks for the library!

**Comment by silkentrance** [comment]
@askogvold what is the problem with the fixes made by the PR? any issues with that?

**Comment by askogvold** [comment]
@silkentrance no, nothing wrong with the fixes, it's great that it works on both now.  - Just suggesting a release on PyPI.

**Comment by silkentrance** [comment]
@askogvold see #3 which targets your inquiry, sort of :grin:

**Comment by askogvold** [comment]
😃
